all.out: test.cpp factorial.cpp flip.cpp isPalindrome.cpp isPrime.cpp query.cpp reset.cpp set.cpp vsum.cpp
	g++ test.cpp factorial.cpp flip.cpp isPalindrome.cpp isPrime.cpp query.cpp reset.cpp set.cpp vsum.cpp -lgtest -lgtest_main -lpthread -o all.out
run:all.out
	./all.out

